server:
  port: 9897
spring:
  application:
    name: local-grpc-client

grpc:
  client:
    local-grpc-server:
      address: 'static://127.0.0.1:8090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext